--find the total customers by countries
select COUNT(customer_key)as total_customers,country from [gold.dim_customers]
group by country
order by total_customers desc
--find the total customers by gender 
select gender,COUNT(customer_key) as total_customers
from [gold.dim_customers]
group by gender
order by total_customers desc
--find the total products by category
select COUNT(product_key)as total_products,category  from [gold.dim_products]
group by category
order by total_products desc
--what is the average cost in each category
select avg(cost)AS Avg_cost,category from [gold.dim_products]
group by category
order by Avg_cost desc
--what is the total revenue generated in each category 
select SUM(price*quantity)as revenue,category from [gold.fact_sales] f
left join [gold.dim_products] p
on f.product_key = p.product_key
group by category
order by revenue desc
--find the total revenue is generated by each castomer
select SUM(price*quantity)as revenue,c.customer_key,first_name,last_name  from [gold.fact_sales] f
left join [gold.dim_customers] c
on  f.customer_key = c.customer_key
group by c.customer_key,first_name,last_name
order by revenue desc
--what is the distribution of sold items across countries
select SUM(quantity)as sold_items,country from [gold.fact_sales] f
left join [gold.dim_customers] c
on  f.customer_key = c.customer_key
group by country
order by sold_items desc